language: go
go:
- 1.11.4
services:
- docker
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' Makefile
- docker build -t gladiusio/node-env .
install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- make releases
deploy:
  provider: releases
  api_key:
    secure: ons781sD7rL4fd7u0YlbQtNp6KcmDknSLkcJK7uj8he9NQLKvx4U1PYw6qCDGk+qOCQrXCFSOD+h3G7pMbk53airnW91y0k4si1XI/JSsQX2BvP50Yv8E1Xi5psMxLqO3r/6Unr0SFhdQzQTi4Olpylt3uR4xuMs+ytlTb3NBkIByGnBR1otU4eLqlIJgnhqMQslTscmEMdYHJ3cIJEr46AccCmDpVatTXiJel2f+zsmfurhQgvdy89MFdNpl278cWRSPL+bOrk/0d4hJ0y1Js4okG5qq1cE2rTJDg7SuLJUI+sUr+IuH+gjZUVFahINCsWOOdaR0FJT2HPZNAzU9v36kZTyI/6F5eLZw7aQHNHHZLmQttkhK/oosFB/Q/wxLNybHK0tkoFI3hICdUvlzQ4FEcep8iqDqMtKpcD7Jwow6VoSU7vlyD7GIYo1cZ64/Z64FJBYialk1OZNiXbkHS6EiB+gd2K2kaU68yrZuXZbJoUmk/BWzS8sLTW+7M+PWFWWeiJy39bxV5tSo5h+FhsJ5ie1aVCsH3kFpK+Hijacu5dTR+VaqL6z/AJSlnmIqbHR1OpMZsOdHMCCQ60Eaqb2EXBnUDeUPHJo+lKjH3Nlmm+qQRBuk9snoKsRE8KOB8tLpOQ6l90K0gqkvg1odrXq/yzPsyDFuGlwZ+B39i4=
  file: 'build/releases/*'
  skip_cleanup: true
  draft: true
  on:
    tags: true