language: go
go:
- 1.11.4
services:
- docker
install:
- docker build -t gladiusio/node-env .
script: make releases
deploy:
  provider: releases
  api_key:
   secure: "VAI7kcIT4CQrtRSlrgBsnKz+65OhBkDmkzHiUnAtIUry78r5bTU4wQlELKWF4DrVb01vnxNaJJxsOlBIXwV0Kg5GTELMet6twUBLoz+1UeqoWdE5cReKQmWE4MsgvYuHL9Ajy5Ts0dUFAb32nRegEednfiC+6P0HZP+wxcbPnCwtKGEQD6atJuZGkNuZFLvAlDtrPPUfV1QcORrpWoWiY1/VpNkuKrfP9zRXivlCdCu5l4eBL/tLvl3D6HKpMPJpffWCgp/Iu8EHUloZXQil9V90dzlD3yusiJgI+7uFkzhdAgQcS2vKY5TB/POFkSuCza1Ae3W+LZDukEbyQXggQq/ZYLJxsoc7nx8KfQ9zxDaFNrTDLzRb75PL8gLMuzg1xRKXn2uHw6TFb7314chdmphXiWR9cGr8T+J/8hoLjGU54tUbfkzgQAcRLwcIhbUCQRHsIxjcG/rEAtUXOrJdyfDhtuCnDDHx6dBFJs2eU5wHUZYhz6zpPmTDBwZ8MZ2fZdwuUpYjjVNAqf1OeJKqIEUCWXiB5HY4h5EBfHvAk38iIAbeB2a6pZgN3WER+O7wAQPjCtKREzBdhYupes161W7UEYq+VUCbZtORdADEaiPjxm6io498EG3fVYF5FeHRuW4efkrDUP4lxLao+ad/qoABvzL8Cd5DZM59H9B0xZ0"
  file: 'build/releases/*'
  skip_cleanup: true
  draft: true
  on:
    tags: true