language: go
go:
- 1.11.4
services:
- docker
install:
- docker build -t gladiusio/node-env .
script: make releases
deploy:
  provider: releases
  api_key:
   secure: "U+pzL71T60macq/8C8/4C5mreDmzP7h285qTQdydQVfXs12xOhQmhKwN7srm2mC2v83X2fXfgE+Mnzpo/i4RxoVVGTpUosH8DwXV4fh9fHndIguzCvUz0IAlbyEbQ4SAkhaev5vaJfE6x5amvIPggLempCXEOHcPHwu9fOVpXROGwDkyc+TD+s1OVsY+r2EJ6n+/nPcT9yVTvuK1EejOmiKpY15KyfXxJ2ts/5mOu4n0gbw1G3fp0URlHjTQ/AgLKvd+V5fry85MM1fuCyllIfxVw93fagtDdTJZVoqRwNLcXSPqDS6J4x+tpWlVnWDcuXj468ecmwkIzZcpJGruOqcpy0e4gjbqM6xUsDZwnKXS/L7E9N69MFBRMle8He9UR86JirbdjY+dhYOFdxMpWUef5p4Ww478fn6W/F7Etp0NOkfVkcGHLp7mxtdUpeBRMpZIkisJQGtN0YczKEDNMFaVgapmFQVrjex94WXTlcLnSWYvKdkciuXlk8jMF7IUXzEZV6nVcGZzpOXfm1m9zHj9B7pWk2bcmPaRty6AirrqFamAsEyRxmiHqbbkFc65NSHZuQcidbdr2Enophudr9f3Id0CEQ+h8lOTA3vywPZbEiTK2RGHf+ZGedHgsDzBpLUk5JXapL7lzizbbNRqzn5QFsZOP2X1vN5tE+15uqA="
  file: 'build/releases/*'
  skip_cleanup: true
  draft: true
  on:
    tags: true