[[constraint]]
  version = "~0.5.2"
  name = "github.com/gladiusio/gladius-networkd"

[[constraint]]
  version = "~0.5.2"
  name = "github.com/gladiusio/gladius-cli"

[[constraint]]
  version = "~0.5.2"
  name = "github.com/gladiusio/gladius-controld"

[prune]
  go-tests = true
  unused-packages = true
