[[constraint]]
  branch = "develop"
  name = "github.com/gladiusio/gladius-networkd"

[[constraint]]
  branch = "develop"
  name = "github.com/gladiusio/gladius-cli"

[[constraint]]
  branch = "develop"
  name = "github.com/gladiusio/gladius-controld"

[prune]
  go-tests = true
  unused-packages = true
