name: gladius
version: git
summary: Gladius CLI
description: Command Line Interface for the Gladius Network

confinement: devmode

parts:
  gladius:
    source: https://github.com/gladiusio/gladius-node/releases/download/0.3.0/gladius-0.3.0-linux-amd64.tar.gz

apps:
  gladius:
    command: gladius